#!/bin/bash

### BEGIN INIT INFO
# Provides:		/usr/bin/trackpoint.sh
# Required-Start:
# Required-Stop:
# Default-Start:	5
# Default-Stop:		0 1 2 3 4 6
# Short-Descriptoin:	Sets trackpoint settings on boot
# Description: Set trackpoint configuration for Sys V on graphical desktop
### END INIT INFO

start() {
/usr/bin/trackpoint.sh start
}

stop() {
/usr/bin/trackpoint.sh stop
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac

exit 0
